-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jul 05, 2021 at 09:40 PM
-- Server version: 5.7.26
-- PHP Version: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `funddb`
--

-- --------------------------------------------------------

--
-- Table structure for table `donations`
--

DROP TABLE IF EXISTS `donations`;
CREATE TABLE IF NOT EXISTS `donations` (
  `d_id` int(11) NOT NULL,
  `d_frid` int(11) NOT NULL,
  `d_amount` int(20) NOT NULL,
  `d_date` datetime NOT NULL,
  `donor_uid` int(11) NOT NULL,
  `d_anon` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `donations`
--

INSERT INTO `donations` (`d_id`, `d_frid`, `d_amount`, `d_date`, `donor_uid`, `d_anon`) VALUES
(1000, 100, 100, '2021-05-21 00:00:00', 1, 0),
(1001, 101, 200, '2021-05-21 00:00:00', 2, 0);

-- --------------------------------------------------------

--
-- Table structure for table `fundraisers`
--

DROP TABLE IF EXISTS `fundraisers`;
CREATE TABLE IF NOT EXISTS `fundraisers` (
  `fr_id` int(11) NOT NULL,
  `fr_title` text NOT NULL,
  `fr_image` varchar(200) NOT NULL DEFAULT 'https://i.ibb.co/5hvJqRS/altrulogo.png',
  `fr_desc` text NOT NULL,
  `fr_category` enum('1','2','3','4','5','6','7','8') DEFAULT NULL,
  `fr_class` enum('Fundraising','Crowdfunding','Crowdsourcing','Covid19','Organisation') NOT NULL,
  `fr_type` enum('Fixed','Flexible') NOT NULL DEFAULT 'Flexible',
  `fr_uid` int(11) NOT NULL,
  `fr_gentime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fr_target` int(20) NOT NULL DEFAULT '0',
  `fr_deadline` datetime NOT NULL,
  `fr_status` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `fundraisers`
--

INSERT INTO `fundraisers` (`fr_id`, `fr_title`, `fr_image`, `fr_desc`, `fr_category`, `fr_class`, `fr_type`, `fr_uid`, `fr_gentime`, `fr_target`, `fr_deadline`, `fr_status`) VALUES
(100, 'Fundraiser for education of kids.', 'https://d2lo9qrcc42lm4.cloudfront.net/Images/News/_contentLarge/India-child-labour-school-holiday-1.jpg?mtime=20180508134303', 'I am located in ahmedabad, and found 6 kids as beggars but i want them to get educated and so raised this crowndfunding .Pls help.', '2', 'Fundraising', 'Flexible', 1, '2021-05-22 15:00:08', 100000, '2021-06-30 17:47:58', 1),
(101, 'Need financial support for a startup.', 'https://img.theweek.in/content/dam/week/news/biz-tech/images/2019/11/7/it-sector-employees-reuters.jpg', 'I want to open my own IT firm for which i need money and your support. Pls help.', '1', 'Crowdfunding', 'Flexible', 2, '2021-05-22 15:00:08', 20000, '2021-05-31 17:48:17', 1),
(102, 'Save The Father Of a 2-Year-Old Daughter From Brain Haemorrhage', 'https://cdn.edudharma.com/images/campaigns/4153/M52M1S9hDUqkvv95zxCEcaFEs5vRAVbxVkejRWZaUU2APDjTKX.png', 'On 24 February 2020, Rohit suddenly collapsed and was rushed to the hospital. The doctor told his wife that he suffered from brain haemorrhage because of which he will have to be admitted to the hospital. He also told her that Rohit’s condition was critical and that he will have to stay in the hospital for a long time for treatment & recovery.\r\n\r\nRohit is the sole earner of his family and unfortunately, he cannot afford to pay for his own treatment.', '1', 'Fundraising', 'Flexible', 3, '2021-05-10 15:38:01', 800000, '2021-06-30 15:38:01', 1),
(103, 'Umeed Ke Sur – Help Himalayas Breathe #TogetherWeCan', 'https://images.financialexpress.com/2021/05/Covid-19-Maharashtra2-5.jpg', 'The mountains are calling all of us for its support. Uttarakhand, being the 2nd state with the highest rate of Covid mortality has innumerable survivors who have lost their means of livelihood. We need to comfort them with our little contribution. This will go a long way in building the healthcare structure in the rural region.', '3', 'Fundraising', 'Flexible', 4, '2021-06-01 15:38:01', 10000000, '2021-07-31 15:38:01', 1),
(104, 'Help NIT Warangal Make It To IGEM 2021', 'https://getmyuni.azureedge.net/college-image/big/national-institute-of-technology-nit-warangal.jpg', 'We are a group of Nineteen highly motivated students who have come together to make a difference! We plan to put our diverse backgrounds, experiences and disciplines together to improve the livelihood of a community i.e., 60 lakh cotton farmers in India.', '2', 'Organisation', 'Flexible', 5, '2021-02-01 15:42:29', 200000, '2021-04-30 15:42:29', 0),
(105, 'Help Students of Delhi Government School to meet their needs .', 'https://i.guim.co.uk/img/media/21a57c77c4ab02db95abaac0a2f5b87b20bf02fb/0_0_3132_1722/master/3132.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=88cbe3601efcffef03f0c9b761004583', 'They lack resources and can be provided with anything that will help them. You are open to donate books, stationaries, bags , clothes , etc. Just come up and contact us for all their blessings.', '2', 'Organisation', 'Flexible', 6, '2021-03-02 15:45:14', 0, '2021-06-30 15:45:14', 0),
(106, 'Help Us To Plant 1 Trillion Tree Worldwide', 'http://im.rediff.com/news/2009/sep/22slide1.jpg', 'The best time to plant trees was yesterday, the next best time is now!\r\nTrees have a massive part to play in the fight against climate change…We are running awareness campaign through social media platforms about Climate Change and Global Warming with our Page \"We Don\'t Deserve This Planet\"\r\nhttps://www.facebook.com/WeDontDeserveEarth/\r\nPlanet warriors need your support.', '3', 'Fundraising', 'Flexible', 7, '2021-04-01 16:32:31', 0, '2021-06-30 16:32:31', 0),
(107, 'Help Us distribute Masks in Rural regions of Maharashtra.', 'https://images.hindustantimes.com/img/2021/04/26/1600x900/Face_Mask_1619439612180_1619439620231.jpeg', 'Our NGO ( Sewa-Dani ) want to distribute masks to each and every corner of Maharashtra and for this we need your support. You can help us in any way you want. You can send us directly masks at the given address or you can donate funds to support Sewa-Dani.', '2', 'Covid19', 'Flexible', 1, '2021-06-26 16:36:24', 0, '2021-08-31 16:32:31', 1),
(108, 'SUPPORT AKSHAYA PATRA\'S COVID-19 RELIEF SERVICE', 'https://blog.akshayapatra.org/wp-content/uploads/2020/04/1160x450-1-1.jpg', 'As the COVID-19 crisis continues to loom over us, The Government of India has taken a strict combat measure by directing a lockdown of the entire nation. At this great hour of need, The Akshaya Patra Foundation, in close coordination with State Governments & District Administration, has stepped in to provide relief by providing food to thousands of people across the country.', '2', 'Covid19', 'Flexible', 2, '2021-06-26 16:39:05', 200000, '2021-09-30 16:36:44', 1),
(111, 'Immunise rural India against Coronavirus', 'https://www.povertyactionlab.org/sites/default/files/styles/large/public/137_1.jpg?itok=KVV6Fjrk', 'The second wave of COVID-19 hit rural India hard. In May, 53% of all new cases were being reported from the country’s hinterlands and accounted for every second death from the virus. The only option to put an end to the pandemic is to vaccinate all eligible citizens. While in cities there is awareness and availability of vaccines, in our rural communities the reality is very different.GiveIndia will partner with state governments and local bodies for training of nurses, paramedics, ASHA workers, and community health workers. We will help bridge the digital divide and facilitate last mile delivery in rural areas especially in aspirational districts.', '3', 'Covid19', 'Flexible', 3, '2021-06-14 16:43:59', 1000000, '2021-10-31 16:43:59', 1),
(112, 'Mission Oxygen- Helping Hospitals Save Lives', 'https://d1vdjc70h9nzd9.cloudfront.net/media/campaign/377000/377638/image/6083dec2a0d5f.jpeg', 'India has witnessed an unprecedented second wave of the Covid-19 pandemic in the last few weeks. The pandemic has claimed over 200,000 lives since the beginning, and the current active caseloads are over 3.5 Million. An estimated 700,000 people are currently in dire need of hospitalisation with oxygen including ICUs. \r\nThere are 3 key areas identified by the team at #missionoxygen:\r\n\r\nImmediate Need: 10L/Min Oxygen Concentrators at healthcare facilities to cater to moderate cases of covid-19\r\nHFNC (Hi Flow Nasal Canulas), and BiPAP machines from critical care as life-saving devices\r\nCaptive Oxygen Generation Plants in Tier-II cities to make hospitals self-sufficient when it comes to Oxygen supplies and doesn\'t run out of Oxygen during peak needs.', '1', 'Covid19', 'Flexible', 4, '2021-03-01 16:43:59', 200000, '2021-11-30 16:43:59', 1),
(113, 'Fundraiser For Suicide Prevention Documentary In India\r\n', 'https://images.citizenmatters.in/wp-content/uploads/sites/3/2019/01/29133751/images-20-678x381.jpeg', 'In August 2020, while researching for our new video to be put out on World Suicide Prevention Day, we started interviewing Suicide Prevention Helpline volunteers, which made us realize that this subject requires a lot more than a few interviews and surface research.We thus urge you to be a part of our cause and make a contribution, however little. Your kindness will not be in vain; there is no measure of how many lives you could touch with your small gesture. While Ubuntu gears up to give flight to our efforts, we hope you will be there to give us wings.', '3', 'Crowdfunding', 'Flexible', 5, '2021-06-01 16:48:50', 0, '2021-06-30 16:48:50', 0),
(114, 'Resoource and Fund collection for college farewell event.', 'http://edtimes.in/wp-content/uploads/2017/04/IMG1111.jpg', 'We the students of IIT Delhi, are planning to give a fantastic farewell to our seniors and this cant be done without you all. If possible pls help us with decoratives, cash , ideas, stalls ,etc. We will be really happy if you help us in any of the way possible.', '2', 'Organisation', 'Flexible', 6, '2021-06-26 16:54:00', 0, '2021-09-24 16:51:54', 0),
(109, 'Help My Brother Fight Colon Cancer', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1625056266/production/images/campaign/342263/Ujjwal_Gupta_mpbj1z_1625056638.jpg', 'I am raising funds for my brother Ujjwal Gupta. He has been diagnosed with Stage 4 Colon Cancer at the young age of 26. Since then, life has been nothing but a rollercoaster of treatments and emotions for us. Ujjwal has already undergone a surgery at Sahyadri Hospital, Pune. Currently, he is being treated by Dr. Minish Jain, Oncologist at Ruby Hall Cancer Center, Pune. The course of the treatment is not small - it amounts to Rs. 1 Crore (INR) and as a middle-class family, this is putting a big strain on our finances and mental health. What\'s worse is, we need the funds at the earliest - which is why, I am reaching out to you today. We need your help in saving Ujjwal. Whatever little you can donate towards the amount of One Crore, will help a lot.', '1', 'Fundraising', 'Fixed', 4, '2021-07-05 18:50:25', 10000000, '2021-07-31 00:00:00', 0),
(110, '1-yrs-old baby Gyanvee has left with very little time, Please help!', 'https://cimages.milaap.org/milaap/image/upload/c_limit,w_603/v1618393421/production/images/uploader_images/Baby_Gyanvee_Mila__7__1618393419.jpg', '\"The doctors have told us that the operation will be very costly, and I am knocking all doors for help. I can\'t lose my angel. I am already under debt, and many times we have to pass days and nights empty stomach due to no work, but we never compromised on her food. Please save my daughter. I will never forget your support\" - cries Satya Pal for help as he loses all hopes.\r\n\r\nWe request you to please support baby Gyanvee and help this family live happily together. Baby Gyanvee needs urgent support for survival. We will be very grateful to you for any support towards baby Gyanvee. Let\'s join hands to save her.', '1', 'Fundraising', 'Fixed', 3, '2021-07-05 18:52:46', 0, '2021-08-18 00:00:00', 0),
(115, 'Help Feed The Stray Dogs Of Hyderabad', 'https://cimages.milaap.org/milaap/image/upload/c_limit,w_1170/v1624708552/production/images/uploader_images/IMG_0320-min_1624708550.jpg', 'EVERY PAW MATTERS is a social organisation that was started in April 2020 by school students across Hyderabad who are animal lovers. We are a small group of around 30 volunteers, and we aim to feed and care for stray dogs and raise awareness about animal issues. We believe that each living-being matters, and no one is superior. As a group, we need at least INR 3,50,000 for our feeding programme to last a year. Any funds raised beyond this will help feed and care for more animals around us on a daily basis.', '4', 'Fundraising', 'Flexible', 8, '2021-07-05 18:55:53', 350000, '2021-07-22 00:00:00', 0),
(116, 'Help Monalisa to reach from Meghalaya to Columbia University!', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1624093955/production/images/campaign/333912/76379B59-B775-48A5-A60E-19660999B6BB_y2twlz_1624094146.jpg', 'I am Monalisa Barman and I come from Tura, a small town of Meghalaya. This is an appeal to help me pursue my Master’s in Public Administration in Columbia University (USA).\r\nI belong to a minority tribe in Meghalaya. Although a matriarchal tribe, women in my tribe have lagged in education due to social, cultural, and economic reasons. I am probably the first woman from my tribe who would step out of this country to pursue higher education. To leverage this opportunity would mean paving a pathway for many like me who could use education as the means to break the wheel.\r\nStudying abroad is expensive, I can’t entirely afford it with my father’s retirement savings or my social work background. This is a vicious cycle – can only those who afford it, deserve it?', '2', 'Fundraising', 'Flexible', 10, '2021-07-05 18:58:11', 7000000, '2021-07-30 00:00:00', 0),
(117, 'Help The Students Of Holy Spirit Continue Their Education', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1625077001/production/images/campaign/332161/Join_the_Movement_1_oruwzk_1625077007.jpg', 'The pandemic has affected the lives of millions of people. We know it has largely affected the lower-income group that survive on daily wages. Education of their children has also taken a big hit.\r\n\r\nWe aim to provide the students of Holy Spirit School with funds to meet their current fee requirements and thereby continue their education.', '2', 'Fundraising', 'Flexible', 12, '2021-07-05 19:00:16', 515000, '2021-07-30 00:00:00', 0),
(118, 'Donate A Sanitary Pad In a mission to help 15000 Women', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1609249260/production/images/campaign/241309/Screenshot_20201229_190931_uvhg79_1609249264.jpg', 'Dear all, \r\nlet’s look at some stark facts about maintaining hygiene environment... Bringing awareness in society by providing the basic needs is very important.for women.', '4', 'Fundraising', 'Flexible', 5, '2021-07-05 19:07:09', 10000, '2021-08-20 00:00:00', 0),
(122, 'Home for a widow', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1472311678/production/images/campaign/images__2__1472311271_1472311676.jpg', 'My goal is to help a widow build a small house. She has no male heir and no source of income. She is meeting her primary needa with the help of her relatives.\r\n\r\nIf you would like to create a difference and bring hope back to the life of widow, please donate.', '5', 'Fundraising', 'Flexible', 5, '2021-07-05 19:13:37', 100000, '2021-08-20 00:00:00', 0),
(119, 'Home for homeless', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1514903379/production/images/campaign/27991/IMG-20180102-WA0074_awt6uk_1514903377.jpg', 'An Orphan in an orphanage should get  love of more than one set of parents and live happily with scores of siblings.  Jeevitha was established in 2003 by a lady who is truly a mother to more than 75 children and provides them home, education, vocational training, care, support and protection.\r\n                   Some of the children here were taken in when they were only few days and some only few weeks old babies.\r\n                  As of now they are housed in a small house paying Rs 80,000. The funds mobilizations have been both in cash and kind with limited donors\r\n        As the number count of children has increased the centre is struggling to provide the facilities like space, care -takers, tuition teachers etc.\r\n          The ashram is looking forward to construct own building with separate building for girsl and boys.\r\n                With the generosity of some donors they have bought a site and now looking for donors to construct a building with basic amenities. ', '5', 'Fundraising', 'Flexible', 8, '2021-07-05 19:15:14', 20000000, '2021-09-08 00:00:00', 0),
(120, 'The NGO That Feeds The Hungry And The Poor', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1583491843/production/images/campaign/145689/FB_IMG_1563087515128_gfdmpq_1583491849.jpg', 'First Human Rights Foundation: The story of a NGO who feeds the poor to fulfill their needs.\r\nEveryday a large number of homeless, poor people who cannot afford a decent meal, line up in neat rows at the railway station  in Belapur. Every man, woman and child wait for their turn to pick up a plate, washes it and sits down in formations.\r\nMany in the line have not eaten for days, but they still wait their turn. Without a hassle, rice is served on each plate followed by dal and Khichdi. This has been going on for more than years, with First Human Rights Foundation sincerely running from end to end serving the food.\r\nIt was then that he decided to hire a cook who is paid a fixed salary every month to start cooking in larger quantities. We Cook approximate  25-20Kg every week if you donate you some funds we will be able to cook about 70-80kg food three times a week. And if we raise a good amount of fund we can give them food everyday.\r\nWe can also increase this from taluka level to district level if we get support from you. We also thank Police force for helping as the distribute the food with us.\r\nWishing u to help.  Remember the poor people are most Generous.\r\nHelping them works in the way god helps us. Poor and rich people die in same manner the why shouldn’t the live in same manner.\r\nOur NGO also works in Andra Pradesh.', '1', 'Organisation', 'Flexible', 7, '2021-07-05 19:17:25', 1500000, '2021-09-24 00:00:00', 0),
(121, 'Solar-is Fundraiser for Solar Panel Installation at NGO schools', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1568010224/production/images/campaign/102393/WhatsApp_Image_2019-02-06_at_3.55.16_PM-2_kbkssm_1568010225.jpg', 'olar-is is an educational and direct engagement campaign aimed an increasing the presence and awareness of solar power and solar energy in communities across India. Ultimately, we aim to provide energy to low-income communities through solar energy. For more information, visit solar-is.net\r\n\r\nThe DTEA Alumni Trust is a charitable organization doing infra and academic work across the Schools of Delhi Tamil Education Association (DTEA) with the objective of extending assistance to the schools to further the cause of education. These schools generally cater to children from economically weaker sections covering nearly 7000 children.\r\n\r\nThis fundraiser hopes to contribute to the installation of solar panels in the next school the trust has identified - Moti Bagh Senior Secondary School, Nanak Pura. The estimated costs for the project is Rs. 7 Lacs.', '1', 'Organisation', 'Flexible', 15, '2021-07-05 19:18:47', 200000, '2021-07-31 00:00:00', 0),
(123, 'Support UNITUS raise $300,000 to help India fight COVID', 'https://images.indianexpress.com/2020/07/ventilator-1200.jpg', 'A dollar-for-dollar donation initiative to help credible healthcare non-profits procure oxygen concentrators  to help India Breathe Again!\r\n\r\nUnitus is a leading venture fund in India that supports early-stage tech startups with India scale and global potential.\r\n \r\nWe support early-stage fintech, healthcare, and jobtech startups with India scale and global emerging market potential. We partner with our investees to build a solid foundation and prepare for growth via funding, strategic and operating support, providing critical connections, and securing growth capital to validate market potential.\r\n\r\nWith the second wave of COVID hitting India, we plan to do the following to do our bit in support of the frontline warriors and thereby, help in procuring the medical supplies.', '2', 'Covid19', 'Flexible', 6, '2021-07-05 19:25:36', 200000, '2021-08-25 00:00:00', 0),
(124, 'Covid treatment', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1622879641/production/images/campaign/321705/FB_IMG_1622879608344_h5poyn_1622879902.jpg', 'I am here to raise funds for my husband Vikram who is 34 years old. Vikram lives in Chennai, Tamil Nadu with me. Vikram is a dentist.\r\n\r\nVikram is suffering from Covid positive for the past few weeks. He is currently admitted and receiving treatment and medication at a private hospital.\r\n\r\nUntil now, we\'ve spent about Rs. 100000. we\'ve arranged the amount from savings.\r\n\r\nIn the next 29 days, we need Rs.300,000 more for further treatment and medication. Please come forward to support my cause. Any contribution will be of immense help. Do contribute and share this campaign link with your friends and family.', '1', 'Covid19', 'Flexible', 12, '2021-07-05 19:28:38', 300000, '2021-07-29 00:00:00', 0),
(125, 'Manisha\'s Covid Treatment', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1621618264/production/images/campaign/308192/Screenshot_2021-05-21-22-09-05-29_c7frgh_1621621776.jpg', 'मैं अपनी बहन मनीषा पैठने के लिए धन जुटा रहीहूँ, जो कोविड से पीड़ित हैं। उनके इलाज के लिए अब तक 1.45 लाख खर्च किए जा चुके हैं।\r\nनिम्न रक्तचाप, कम हीमोग्लोबिन, कम WBC गिनती के लिए उनका इलाज भी इसी अवधि के दौरान हुआ।\r\nकोविड उपचार के साथ-साथ उसे 3 यूनिट रक्त दिया है।\r\nमनीषा ने पिछले साल कोविड महामारी शुरू होने के बाद अपनी नौकरी खो दी थी।\r\n\r\nअब हमारे पास अगले liver ke इलाज के लिए और धन नहीं हैं। ', '1', 'Covid19', 'Fixed', 19, '2021-07-05 19:30:12', 450000, '2021-07-19 00:00:00', 0),
(126, 'Support Ramakrishna Mission To Provide Medicine During Covid', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1619623191/production/images/campaign/281803/Free_meal_is_served_at_IPD_Section_u60iro_1619623198.jpg', 'During the first endemic period, our Home of Service conducted extensive relief works supplying food articles, medicines, sanitary items, drinking water etc. to the Local poor, Rural mass of the adjacent districts, and migrant labours. For that entire period, our OPD and emergency services were fully functional; however, we had to close down the Indoor Hospital due to the non-availability of medical and other staff under the Lockdown Restrictions. As a result, the Revenue generation from the Hospital front was badly affected leading to almost zero level and has resulted in a huge deficit of around Rupees Three (3) Crores as of 31.03.2021.\r\n\r\nDuring the present second wave of C-19, Varanari is worst affected. In our Hospital, we are now running two Covid Wards — one with 24 beds for general patients and the other with 16 beds/cabins for our staff and inmates. \r\n\r\nRevenue generation is severely affected again and at present, the very sustainability of all the Service Programmes run by us are under threat. It is important to mention here that this Home of Service does not get any Financial Assistance/Grant from Central or State Government to run or maintain such noble services.\r\n\r\nUnder such circumstances, we earnestly seek your wholehearted support to continue the Century-Old Service Activities run by this Home of Service. ', '3', 'Covid19', 'Flexible', 1, '2021-07-05 19:32:08', 1800000, '2021-07-23 00:00:00', 0),
(127, 'Help me patent my idea of an app and website', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1562056369/production/images/campaign/87983/665062-stress_zotyz7_1562056468.jpg', 'I am raising funds for a patent of my app and website. This initiative is about increasing the knowledge of a student whether in a school or in a college without charging them anything. I am an engineering student and wants these funds to patent this idea and develop it which will surely help the students in India to increase their knowledge. Our website and app are aimed at creating a bond between students, school/college and teachers. We will go talk to each college and school and our system installed at the same so that the students can use it to increase their knowledge about their subjects. This idea popped up in my mind as a solution to a problem which I was going through and almost every student goes through at least once in his/her student life. See I just want to make a change in the education sector by bringing our product in the market which I know is a game changer. I am highly passionate about this project because it can solve the problems of every student in this globe and I will anything I can to make this product available to each and every school and college in the world and thus to each student. Our platform will always remain free for students with no terms and conditions. They can directly use it once it is approved and installed by there respective colleges and schools. I also promise neither now nor in the future, it will cost nothing to students, not even a single penny. The funds which will be raised will be used to patent our idea first and then buying the necessary servers and products required for the same. Please help me fulfill my dream by contributing to my project or sharing this fundraiser with your friends and family!', '4', 'Crowdfunding', 'Fixed', 10, '2021-07-05 19:39:17', 120000, '2021-09-08 00:00:00', 0),
(128, 'Help For an IDEA', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1589882073/production/images/campaign/115936/20200519_152411_0000_dyxeji_1589883059.jpg', 'Due to this COVID-19 pandemic, our lives have just blown up, everything has almost changed, and because of this an idea came in my head, let me explain you briefly.\r\n\r\nThe idea circles around \"social distancing\", the gift of COVID-19, so what let\'s skip to what exactly the idea is.\r\n\r\nI have been running an online shopping store, delivery products locally in my home town, which has almost 2.5 million residents, yeah that\'s a huge number of people\r\n\r\nSo we are having so much problem shipping products to customers, due to the Virus, there are several restrictions, as we have to maintain social distancing. So we had an idea to Deliver products through \'DRONES\', and we realised that this is the perfect situation, opportunity to start delivering products to customers place through a drone.\r\n\r\n\r\nThe funds raised will be utilised to buy drones for kick-starting the plan/idea.\r\n\r\nWith this much funds we\'ll able to stock 2 drones capable of lifting 500 grams of weight, which is sufficient for Delivery our products. The drone will be equipped with a camera, gps system, and will be able to fly high enough.', '2', 'Crowdfunding', 'Flexible', 9, '2021-07-05 19:43:38', 50000, '2021-07-31 00:00:00', 0),
(129, 'Help Yogendra To Present His Idea In China For Social Benefits', 'https://i.ibb.co/5hvJqRS/altrulogo.png', 'I am selected for the China India youth forum but the program cost is 80,000 Indian rupees, I belong to a retired army person\'s family so I don\'t have enough money for this, my idea is related to increase farmer\'s income so it would bring benefits to society. Any help would be highly appreciated.  ', '2', 'Crowdfunding', 'Flexible', 19, '2021-07-05 19:45:44', 80000, '2021-07-22 00:00:00', 0),
(130, 'Help for Tejas Mushrooms Farm startup', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1492936482/production/images/campaign/DSC_0907_1492933224_1492936480.jpg', 'Basically, I\'m a software engineer worked with big MNCs, then quit my job to take care of my hubby and two lovely kids. Even though  I enjoyed my motherhood something keeps striking me that I need to achieve something.Before 8 months  I came across the word mushroom farming but never took it seriously. People I enquired told its difficult to maintain so we left it. Everyone was too much aware of oyster mushrooms and button mushrooms.Then when I continued my research and watched YouTube videos (Telugu, Thai, Hindi) of course I don\'t know much of these languages but based on the visuals I gathered things, found out a tropical mushroom(milky mushroom) that could grow in 25-35 degrees Celsius.', '1', 'Crowdfunding', 'Flexible', 18, '2021-07-05 19:47:42', 100000, '2021-09-17 00:00:00', 0),
(131, 'Project Muskurahat', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1529666611/production/images/campaign/40217/18238542_990161644420395_2415220537910951509_o_bmnzhb_1529667054.jpg', 'Muskurahat foundation as an NGO works a lot in the field of child welfare, education and women empowerment. Being a youth of this generation it is very important to bring about a change in our society. As an intern I want to try my best to help the underprivileged. No amount is a small amount every contribution matters. Let\'s bring a smile today. A \'muskurahat\' in their faces gifted by you!😊', '3', 'Crowdfunding', 'Flexible', 2, '2021-07-05 19:49:18', 10000, '2021-07-28 00:00:00', 0),
(132, 'Support Research On Fire Safety.', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1564371827/production/images/campaign/93511/images_1_cjytu8_1564372907.jpg', 'I am a research scholar of Cochin University of Science and Technology, Kerala. Our aim is to conduct an experimental study of open and enclosed fires of different size and determine the heat transfer, smoke production and spread of fire. Also we develop a computer simulation of real fire growth in buildings and vehicles. We can calculate the fire safety distance from the fire source and that data will help us to safe fire fighting and emergency evacuation. We can categorize the fire severity area and as the results reduce the impact of fire accidents or prevent the fire accidents.\r\nFor the smooth running of my research need some financial support and I expect our findings  make a new era in fire fighting and prevention. I assure that our research is more relevant in current days.', '5', 'Crowdfunding', 'Flexible', 4, '2021-07-05 19:51:23', 500000, '2021-07-30 00:00:00', 0),
(133, 'Translational breast cancer research', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1559197409/production/images/campaign/81144/FB_IMG_1559196944237_tnrto2_1559197421.jpg', 'Consider the following facts: In breast cancer alone, there has been over 2000 inhibitors developed in research labs, though only one or two are effective in clinics.\r\nThus , undoubtedly, there is an yawning gap between research in labs and clinics.\r\nWe need to reduce this gap.\r\nWe need to stratify patients better or target drugs better to patients Who will benefit from the different inhibitors.\r\nWe at Dr Jeyapaul Cancer Foundation Trust are committed to raise funds for design of treatment targeted to be effective in the clinics.\r\nSo we are a charitable, non profit organisation dedicated to translational research work (60%of funds) and for treatment of young patients not able to afford it ( 40% of funds)', '5', 'Crowdfunding', 'Flexible', 2, '2021-07-05 19:52:19', 200000, '2021-07-26 00:00:00', 0),
(134, 'Cheekolite (Made in India app / Alternate to Tiktok)', 'https://cimages.milaap.org/milaap/image/upload/c_fill,g_faces,h_452,w_603/v1594708676/production/images/campaign/193593/Screenshot_20200714-120653_Cheekolite_mthq8a_1594709317.jpg', 'We are a team of young, mature, and energetic explorers and we have created an indian made app by the name of Cheekolite, which is a formidable alternate to TikTok. We need funds to pursue our cumulative dream of developing anf creating everything in india, to become self-sufficient, and self-reliant. This app can be overviewed by following this url -: https://play.google.com/store/apps/details?id=cheekolite.gpslab.com\r\n\r\nPls help us be a part of contributing to Strong India, Aatmnirbhar Bhaarat.', '4', 'Crowdfunding', 'Flexible', 9, '2021-07-05 19:56:34', 200000, '2021-07-31 00:00:00', 0),
(135, 'Labour for Building Construction', 'https://bsmedia.business-standard.com/_media/bs/img/article/2020-09/09/full/1599670712-5941.jpg', 'Need labour for construction of buildings in Mumbai', '3', 'Crowdsourcing', 'Flexible', 19, '2021-07-05 19:58:56', 2000, '2021-07-31 00:00:00', 0),
(136, 'Labour for School in Delhi', 'https://www.livelaw.in/h-upload/2020/09/27/382051-workers-labourers.jpg', 'Need labour', '3', 'Crowdsourcing', 'Flexible', 11, '2021-07-05 20:00:16', 0, '2021-08-18 00:00:00', 0),
(137, 'Book Distribution in Slum Areas', 'https://wecarewelfaretrust.org/assets/img/events-page/book-distribution-slum-area/1.jpg', 'As books have a wonderful way of helping slum children develop, within the world of books you can find imagination and creativity. In this bustling digital world, it is more important than ever to create a moment to slow down and enjoy and a book is a great way to do that. We aim to distribute some activity and colour books for making learning the alphabet fun with this colourful workbook, recognize letter and letter-sound relationship and important emergent children.', '2', 'Crowdsourcing', 'Flexible', 21, '2021-07-05 20:02:48', 0, '2021-09-08 00:00:00', 0),
(138, 'Ideas Wanted!', 'https://cdn.pixabay.com/photo/2018/01/08/21/19/idea-3070332_1280.jpg', 'I am working on app to save the environment by gamifying little tasks that we do in our day-to-day life. Looking out for ideators to help solve this problem.', '1', 'Crowdsourcing', 'Flexible', 20, '2021-07-05 20:06:55', 0, '2021-08-20 00:00:00', 0),
(139, 'Graphic Designer Community ', 'https://99designs-blog.imgix.net/blog/wp-content/uploads/2019/09/Graphic_design_resources_3_jpg_kjGz3g_s.jpg?auto=format&q=60&w=1280&h=960&fit=crop&crop=faces', 'Require ideators who can visualize the future of graphic design. Contact in case interested.', '1', 'Crowdsourcing', 'Flexible', 21, '2021-07-05 20:08:22', 0, '2021-08-27 00:00:00', 0),
(140, 'Need Grains urgently!', 'https://i2.wp.com/www.eatthis.com/wp-content/uploads/2019/06/grains.jpg?fit=1200%2C879&ssl=1', 'We are hungry! We need food in Anandpur. Please help us by supplying grains. ', '2', 'Crowdsourcing', 'Flexible', 23, '2021-07-05 20:09:59', 0, '2021-07-30 00:00:00', 0);

-- --------------------------------------------------------

--
-- Table structure for table `support`
--

DROP TABLE IF EXISTS `support`;
CREATE TABLE IF NOT EXISTS `support` (
  `s_id` int(11) NOT NULL AUTO_INCREMENT,
  `s_bid` int(11) NOT NULL,
  `s_amount` int(20) NOT NULL,
  `s_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `s_did` int(11) NOT NULL,
  `s_anon` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`s_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `support`
--

INSERT INTO `support` (`s_id`, `s_bid`, `s_amount`, `s_date`, `s_did`, `s_anon`) VALUES
(1, 2, 300, '2021-07-15 00:00:00', 1, 0),
(2, 1, 300, '2021-07-03 16:20:39', 2, 0);

-- --------------------------------------------------------

--
-- Table structure for table `user_info`
--

DROP TABLE IF EXISTS `user_info`;
CREATE TABLE IF NOT EXISTS `user_info` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `City` varchar(100) NOT NULL,
  `State` varchar(20) NOT NULL,
  `Country` varchar(12) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Create_pw` text NOT NULL,
  `Confirm_pw` text NOT NULL,
  `Mobile_no` text NOT NULL,
  `Tamt_donated` int(10) NOT NULL DEFAULT '0',
  `Tamt_gained` int(10) NOT NULL DEFAULT '0',
  `SupportStatus` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `Email` (`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user_info`
--

INSERT INTO `user_info` (`user_id`, `Name`, `City`, `State`, `Country`, `Email`, `Create_pw`, `Confirm_pw`, `Mobile_no`, `Tamt_donated`, `Tamt_gained`, `SupportStatus`) VALUES
(1, 'Vritika Naik', 'Mapusa', 'Goa', 'India', 'vritikan@gmail.com', 'vriti', 'vriti', '9130335324', 55500, 0, 1),
(2, 'Erina', 'Kolkata', 'West Bengal', 'India', 'erina@gmail.com', 'erina@123', 'erina@123', '7454918897', 10000, 0, 1),
(3, 'Anna', 'Mapusa', 'Goa', 'India', 'anna@outlook.com', 'WOHOO', 'WOHOO', '92323134213', 10, 0, 1),
(4, 'Sana', 'Mumbai', 'Maharashtra', 'India', 'sanasathi@gmail.com', 'sanasathi', 'sanasathi', '9423984242', 40000, 0, 0),
(5, 'Sudhakar', 'Udaipur', 'Rajasthan', 'India', 'sudhakar@outlook.com', 'sudhakar', 'sudhakar', '9182344351', 10000, 0, 1),
(6, 'Amelia', 'Noida', 'Delhi', 'India', 'amelia@ymail.com', 'amelia', 'amelia', '9231342839', 0, 0, 0),
(7, 'admin', 'Mapusa', 'Goa', 'India', 'vritika@gmail.com', 'MainAdminHoon', 'MainAdminHoon', '9130335324', 0, 0, 0),
(8, 'Rahul', 'Ahmedabad', 'Gujarat', 'India', 'rahunair@gmail.com', 'rahul@123', 'rahul@123', '7454918899', 938232, 0, 0),
(9, 'Anjali', 'Virar', 'Maharashtra', 'India', 'anjali@gmail.com', 'anjali', 'anjali', '9284395332', 100, 0, 0),
(11, 'Anjana Deshmukh', 'Navi Mumbai', 'Maharashtra', 'India', 'anjanad@gmail.com', 'anjana', 'anjana', '7281736283', 0, 0, 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
