export const  FundraiserData = [
    {
        id:1,
        date: '17/06/2021',
        name: "Child Labour Abolishment",
        shipTo: "Gyaan Ganga NGO",
        paymentMethod: "Credit Card",
        amount: 25000,
    },
    {
        id:2,
        date: '08/05/2021',
        name: "Let's Build a Home for Stray Dogs",
        shipTo: "Pet 24x7",
        paymentMethod: "Credit Card",
        amount: 10000,
      },
      {
        id:3,
        date: '09/04/2021',
        name: "Help Vaidehi go to Canada for her education",
        shipTo: "Vaidehi Dekhne",
        paymentMethod: "Credit Card",
        amount: 5500,
      },
      {
        id:4,
        date: '17/03/2021',
        name: "Support My Idea",
        shipTo: "Venkatesh Raj",
        paymentMethod: "Credit Card",
        amount: 5000,
      },
      {
        id:5,
        date: '23/01/2021',
        name: "Help Save Adya's Life",
        shipTo: "Adyeshwar Kumar",
        paymentMethod: "Credit Card",
        amount: 10000,
      },
  ];